checks:
  file-lines:
    enabled: true
    config:
      threshold: 500
plugins:
#  bandit:
#    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
    checks:
      Similar code:
        enabled: false
#  pep8:
#    enabled: true
#  pylint:
#    enabled: true
  radon:
    enabled: true
    config: 
      threshold: "C"
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - secsgem/**
