version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  apt_packages:
    - default-jre-headless
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install